CC = gcc
CFLAGS = -Wall -g
LDFLAGS = -lm

PROG = grafo

all: grafo

principal.o: principal.c

memo.o: memo.c memo.h

vertice.o: vertice.c vertice.h

lista.o: lista.c lista.h

grafo.o: grafo.c grafo.h

fila.o: fila.c fila.h

grafo: principal.o memo.o vertice.o lista.o grafo.o fila.o
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)
	
clean:
	rm -f *.o $(PROG)
